server:
  port: 8761
eureka:
  client:
    register-with-eureka: false #表示是否将自己注册到Eureka Server，默认为true。由于当前应用就是EurekaServer，故而设为false
    fetch-registry: false       #是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的eureka server，不需要同步其他得Eureka Server节点的数据，故设为false。
    service-url:
      defaultZone: http://localhost:8761/eureka #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址，默认http://localhost:8761/eureka，多个地址可使用,分隔
security:
  basic:
    enabled: true #开启基于HTTP basic的认证
  user:
    name: user    #配置登录的账号user
    password: 123 #配置登录的密码123